version: '3'

services:
  traefik:
    image: traefik:v2.3
    command: --configfile /etc/traefik/traefik.toml
    restart: "always"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik/:ro 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.test`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      # Attach the gateway network
      - default

networks:
  default:
    external:
      name: gateway
